import bcrypt from 'bcryptjs';
import {v4 as uuidv4} from 'uuid';
const Id = uuidv4()
console.log(uuidv4())

const data = {
  users: [
    {
      firstName: 'John',
      lastName: 'Doe',
      email: 'admin@example.com',
      password: bcrypt.hashSync('admin1234'),
      phone: '9012345678',
      isAdmin: true,
    },
  ],
  products: [
    {
      name: 'Abacha',
      volume: '1 litre',
      servings: 4,
      slug: 'abacha',
      id: Id,
      category: 'Salads',
      image: `/images/abacha.png`,
      price: 5000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous Abacha and Ugba garnished with fish, kpomo and vegetables.',
    },
    {
      name: 'Beans Porridge',
      volume: '1 litre',
      servings: 4,
      slug: 'beans_porridge',
      id: Id,
      category: 'Porridges',
      image: `/images/beans_porridge.png`,
      price: 3000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of delicious beans porridge garnished with plantains and your choice of either beef, fish or chicken.',
    },

    // Eguisi
    {
      name: 'Eguisi Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'eguisi_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/eguisi_soup.png`,
      price: 4000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Eguisi Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'eguisi_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/eguisi_soup.png`,
      price: 6000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Eguisi Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'eguisi_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/eguisi_soup.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    // Oha
    {
      name: 'Oha Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'oha_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/oha_soup.png`,
      price: 4000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Oha Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'oha_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/oha_soup.png`,
      price: 6000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Oha Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'oha_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/oha_soup.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Afang
    {
      name: 'Afang Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'afang_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/afang_soup.png`,
      price: 4000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Afang Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'afang_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/afang_soup.png`,
      price: 6000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Afang Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'afang_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/afang_soup.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Banga
    {
      name: 'Banga Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'banga_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/banga_soup.png`,
      price: 4500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Banga Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'banga_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/banga_soup.png`,
      price: 6500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Banga Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'banga_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/banga_soup.png`,
      price: 8000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Bitter Leaf
    {
      name: 'Bitter Leaf Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'bitter_leaf_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/bitterleaf_soup.png`,
      price: 4000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    {
      name: 'Bitter Leaf Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'bitter_leaf_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/bitterleaf_soup.png`,
      price: 6000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    {
      name: 'Bitter Leaf Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'bitter_leaf_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/bitterleaf_soup.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    //Vegetable
    {
      name: 'Vegetable Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'veg_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/vegetable_soup.png`,
      price: 4000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Vegetable Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'veg_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/vegetable_soup.png`,
      price: 6000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Vegetable Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'veg_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/vegetable_soup.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    // Okra
    {
      name: 'Okra Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'okra_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/okra_soup.png`,
      price: 4000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Okra Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'okra_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/okra_soup.png`,
      price: 6000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Okra Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'okra_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/okra_soup.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Ewedu
    {
      name: 'Ewedu Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'ewedu_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/ewedu_soup.png`,
      price: 3000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    {
      name: 'Ewedu Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'ewedu_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/ewedu_soup.png`,
      price: 4500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    {
      name: 'Ewedu Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'ewedu_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/ewedu_soup.png`,
      price: 6000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    // Gbegiri
    {
      name: 'Gbegiri Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'gbegiri_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/gbegiri_soup.png`,
      price: 3500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    {
      name: 'Gbegiri Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'gbegiri_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/gbegiri_soup.png`,
      price: 5500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    {
      name: 'Gbegiri Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'gbegiri_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/gbegiri_soup.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    // Tomato Stew
    {
      name: 'Tomato Stew',
      volume: '1 litre',
      servings: 4,
      slug: 'tomato_stew_1l',
      id: Id,
      category: 'Stews',
      image: `/images/tomato_stew.png`,
      price: 3500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Tomato Stew',
      volume: '2 litres',
      servings: 8,
      slug: 'tomato_stew_2l',
      id: Id,
      category: 'Stews',
      image: `/images/tomato_stew.png`,
      price: 5500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Tomato Stew',
      volume: '2.5 litres',
      servings: 12,
      slug: 'tomato_stew_2.5l',
      id: Id,
      category: 'Stews',
      image: `/images/tomato_stew.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    // Ofada Sauce
    {
      name: 'Ofada Sauce',
      volume: '1 litre',
      servings: 4,
      slug: 'ofada_sauce_1l',
      id: Id,
      category: 'Sauces',
      image: `/images/ofada_sauce.png`,
      price: 5000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    {
      name: 'Ofada Sauce',
      volume: '2 litres',
      servings: 8,
      slug: 'ofada_sauce_2l',
      id: Id,
      category: 'Sauces',
      image: `/images/ofada_sauce.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    {
      name: 'Ofada Sauce',
      volume: '2.5 litres',
      servings: 12,
      slug: 'ofada_sauce_2.5l',
      id: Id,
      category: 'Sauces',
      image: `/images/ofada_sauce.png`,
      price: 9500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    // White Soup
    {
      name: 'White Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'white_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/white_soup.png`,
      price: 4500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    {
      name: 'White Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'white_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/white_soup.png`,
      price: 6500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    {
      name: 'White Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'white_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/white_soup.png`,
      price: 8500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    // Eforiro
    {
      name: 'Eforiro Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'efo_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/efo_soup.png`,
      price: 4000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    {
      name: 'Eforiro Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'efo_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/efo_soup.png`,
      price: 5500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    {
      name: 'Eforiro Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'efo_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/efo_soup.png`,
      price: 7500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    // Curry Sauce
    {
      name: 'Curry Sauce',
      volume: '1 litre',
      servings: 4,
      slug: 'curry_sauce_1l',
      id: Id,
      category: 'Sauces',
      image: `/images/curry_sauce.png`,
      price: 5000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    {
      name: 'Curry Sauce',
      volume: '2 litres',
      servings: 8,
      slug: 'curry_sauce_2l',
      id: Id,
      category: 'Sauces',
      image: `/images/curry_sauce.png`,
      price: 7000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    {
      name: 'Curry Sauce',
      volume: '2.5 litres',
      servings: 12,
      slug: 'curry_sauce_2.5l',
      id: Id,
      category: 'Sauces',
      image: `/images/curry_sauce.png`,
      price: 8500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    // Fisherman Soup
    {
      name: 'Fisherman Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'fisherman_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/fisherman_soup.png`,
      price: 6500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    {
      name: 'Fisherman Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'fisherman_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/fisherman_soup.png`,
      price: 9500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    {
      name: 'Fisherman Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fisherman_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/fisherman_soup.png`,
      price: 11000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    // Catfish Pepper Soup
    {
      name: 'Catfish Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'catfish_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/catfish_peppersoup.png`,
      price: 6500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    {
      name: 'Catfish Pepper Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'catfish_peppersoup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/catfish_peppersoup.png`,
      price: 8500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    {
      name: 'Catfish Pepper Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'catfish_peppersoup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/catfish_peppersoup.png`,
      price: 11000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    // Goat Meat Pepper Soup
    {
      name: 'Goat Meat Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'goatmeat_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/goatmeat_peppersoup.png`,
      price: 4500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    {
      name: 'Goat Meat Pepper Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'goatmeat_peppersoup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/goatmeat_peppersoup.png`,
      price: 6500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    {
      name: 'Goat Meat Pepper Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'goatmeat_peppersoup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/goatmeat_peppersoup.png`,
      price: 8000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    // Cow Tail Pepper Soup
    {
      name: 'Cow Tail Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'cowtail_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/cowtail_peppersoup.png`,
      price: 4500,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with cow tail.',
    },
    // Yam Porridge
    {
      name: 'Yam Porridge',
      volume: '1 litre',
      servings: 4,
      slug: 'yam_porridge',
      id: Id,
      category: 'Porridges',
      image: `/images/yam_porridge.png`,
      price: 3000,
      vendor: 'Always Hot Restaurant',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'A pot of delicious yam porridge garnished with vegetables and your choice of either beef, fish or chicken.',
    },
  ],
};

export default data;
