import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';
const Id = uuidv4();
console.log(uuidv4());

const data = {
  users: [
    {
      firstName: 'John',
      lastName: 'Doe',
      email: 'admin@example.com',
      password: bcrypt.hashSync('admin1234'),
      phone: '9012345678',
      isAdmin: true,
      isEmailVerified: true,
    },
  ],
  products: [
    // Abacha
    {
      name: 'Abacha',
      volume: '1 litre',
      servings: 4,
      slug: 'abacha_1l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790214/eeokusifmwi8sji6afz0.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous Abacha and Ugba garnished with fish, kpomo and vegetables.',
    },
    {
      name: 'Abacha',
      volume: '2 litres',
      servings: 8,
      slug: 'abacha_2l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790214/eeokusifmwi8sji6afz0.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous Abacha and Ugba garnished with fish, kpomo and vegetables.',
    },
    {
      name: 'Abacha',
      volume: '2.5 litres',
      servings: 12,
      slug: 'abacha_2.5l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790214/eeokusifmwi8sji6afz0.png`,
      price: 9000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous Abacha and Ugba garnished with fish, kpomo and vegetables.',
    },
    // Chicken Salad
    {
      name: 'Chicken Salad',
      volume: '1 litre',
      servings: 4,
      slug: 'chicken_salad_1l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790299/np3nlkmknwev38q2e2fh.png`,
      price: 2500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous chicken salad.',
    },
    {
      name: 'Chicken Salad',
      volume: '2 litres',
      servings: 8,
      slug: 'chicken_salad_2l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790299/np3nlkmknwev38q2e2fh.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous chicken salad.',
    },
    {
      name: 'Chicken Salad',
      volume: '2.5 litres',
      servings: 12,
      slug: 'chicken_salad_2.5l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790299/np3nlkmknwev38q2e2fh.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous chicken salad.',
    },
    // Fish Salad
    {
      name: 'Fish Salad',
      volume: '1 litre',
      servings: 4,
      slug: 'fish_salad_1l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790370/e3vnjve7wlufqwrknetl.png`,
      price: 2500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous fish salad.',
    },
    {
      name: 'Fish Salad',
      volume: '2 litres',
      servings: 8,
      slug: 'fish_salad_2l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790370/e3vnjve7wlufqwrknetl.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous fish salad.',
    },
    {
      name: 'Fish Salad',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fish_salad_2.5l',
      id: Id,
      category: 'Salads',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790370/e3vnjve7wlufqwrknetl.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous fish salad.',
    },
    // Native Rice
    {
      name: 'Native Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'native_rice_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790425/fp5dumxb3wmzqyzo1tze.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian native rice.',
    },
    {
      name: 'Native Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'native_rice_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790425/fp5dumxb3wmzqyzo1tze.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian native rice.',
    },
    {
      name: 'Native Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'native_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790425/fp5dumxb3wmzqyzo1tze.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian native rice.',
    },
    // Fried Rice
    {
      name: 'Fried Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'fried_rice_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790471/xbbl5duwngqc62sbr3rz.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian fried rice.',
    },
    {
      name: 'Fried Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'fried_rice_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790471/xbbl5duwngqc62sbr3rz.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian fried rice.',
    },
    {
      name: 'Fried Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fried_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790471/xbbl5duwngqc62sbr3rz.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian fried rice.',
    },
    // Jollof Rice
    {
      name: 'Jollof Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'jollof_rice_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790508/czhkhxdfaey4jpjqkeni.png`,
      featuredImage: `/images/jollof_rice-banner.png`,
      isFeatured: true,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian jollof rice.',
    },
    {
      name: 'Jollof Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'jollof_rice_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790508/czhkhxdfaey4jpjqkeni.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian jollof rice.',
    },
    {
      name: 'Jollof Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'jollof_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790508/czhkhxdfaey4jpjqkeni.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian jollof rice.',
    },
    // White Rice
    {
      name: 'White Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'white_rice_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790561/dce6to2nms6dtdqlflyw.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice.',
    },
    {
      name: 'White Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'white_rice_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790561/dce6to2nms6dtdqlflyw.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice.',
    },
    {
      name: 'White Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'white_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790561/dce6to2nms6dtdqlflyw.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice.',
    },
    // Ofada Rice
    {
      name: 'Ofada Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'ofada_rice_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790600/lgqfrw68mee67gljryz9.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian ofada rice.',
    },
    {
      name: 'Ofada Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'ofada_rice_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790600/lgqfrw68mee67gljryz9.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian ofada rice.',
    },
    {
      name: 'Ofada Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'ofada_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790600/lgqfrw68mee67gljryz9.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian ofada rice.',
    },
    // Palm Oil Rice
    {
      name: 'Palm Oil Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'palm_rice_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790675/mbp2gg7vhvivhh3l5mpf.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian palm oil rice.',
    },
    {
      name: 'Palm Oil Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'palm_rice_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790675/mbp2gg7vhvivhh3l5mpf.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian palm oil rice.',
    },
    {
      name: 'Palm Oil Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'palm_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790675/mbp2gg7vhvivhh3l5mpf.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian palm oil rice.',
    },
    // Seafood Fried Rice
    {
      name: 'Seafood Fried Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'seafood_rice_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790734/vx4ffphdnni6o0tlfxmp.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked seafood fried rice.',
    },
    {
      name: 'Seafood Fried Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'seafood_rice_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790734/vx4ffphdnni6o0tlfxmp.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked seafood fried rice.',
    },
    {
      name: 'Seafood Fried Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'seafood_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790734/vx4ffphdnni6o0tlfxmp.png`,
      price: 10000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked seafood fried rice.',
    },
    //White Rice & Beans
    {
      name: 'White Rice & Beans',
      volume: '1 litre',
      servings: 4,
      slug: 'w_rice_beans_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790778/napy2wwzqkrjwtrmcob7.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice and beans .',
    },
    {
      name: 'White Rice & Beans',
      volume: '2 litres',
      servings: 8,
      slug: 'w_rice_beans_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790778/napy2wwzqkrjwtrmcob7.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice and beans .',
    },
    {
      name: 'White Rice & Beans',
      volume: '2.5 litres',
      servings: 12,
      slug: 'w_rice_beans_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790778/napy2wwzqkrjwtrmcob7.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice and beans .',
    },
    // Jollof Rice & Beans
    {
      name: 'Jollof Rice & Beans',
      volume: '1 litre',
      servings: 4,
      slug: 'j_rice_beans_1l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790823/od2ejum0lkdgjaizaq7c.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked jollof rice and beans .',
    },
    {
      name: 'Jollof Rice & Beans',
      volume: '2 litres',
      servings: 8,
      slug: 'j_rice_beans_2l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790823/od2ejum0lkdgjaizaq7c.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked jollof rice and beans .',
    },
    {
      name: 'Jollof Rice & Beans',
      volume: '2.5 litres',
      servings: 12,
      slug: 'j_rice_beans_2.5l',
      id: Id,
      category: 'Rice',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790823/od2ejum0lkdgjaizaq7c.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked jollof rice and beans .',
    },
    // Jollof Spaghetti
    {
      name: 'Jollof Spaghetti',
      volume: '1 litre',
      servings: 4,
      slug: 'jollof_spaghetti_1l',
      id: Id,
      category: 'Pasta',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790863/bxmqsf8lznjz4tr5do6m.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian jollof spaghetti.',
    },
    {
      name: 'Jollof Spaghetti',
      volume: '2 litres',
      servings: 8,
      slug: 'jollof_spaghetti_2l',
      id: Id,
      category: 'Pasta',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790863/bxmqsf8lznjz4tr5do6m.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian jollof spaghetti.',
    },
    {
      name: 'Jollof Spaghetti',
      volume: '2.5 litres',
      servings: 12,
      slug: 'jollof_spaghetti_2.5l',
      id: Id,
      category: 'Pasta',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790863/bxmqsf8lznjz4tr5do6m.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian jollof spaghetti.',
    },
    // Seafood Spaghetti
    {
      name: 'Seafood Spaghetti',
      volume: '1 litre',
      servings: 4,
      slug: 'seafood_spaghetti_1l',
      id: Id,
      category: 'Pasta',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790903/khihfx0uytahqt4y2pge.png`,
      featuredImage: `/images/seafood_spaghetti-banner.png`,
      isFeatured: true,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian seafood spaghetti.',
    },
    {
      name: 'Seafood Spaghetti',
      volume: '2 litres',
      servings: 8,
      slug: 'seafood_spaghetti_2l',
      id: Id,
      category: 'Pasta',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790903/khihfx0uytahqt4y2pge.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian seafood spaghetti.',
    },
    {
      name: 'Seafood Spaghetti',
      volume: '2.5 litres',
      servings: 12,
      slug: 'seafood_spaghetti_2.5l',
      id: Id,
      category: 'Pasta',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790903/khihfx0uytahqt4y2pge.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian seafood spaghetti.',
    },
    // Asun
    {
      name: 'Asun',
      volume: '1 litre',
      servings: 4,
      slug: 'asun_1l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790943/em2zviywyhg8wuxaciwr.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 4,
      numReviews: 15,
      countInStock: 20,
      description: 'A pot of sumptuous freshly roasted asun barbeque.',
    },
    {
      name: 'Asun',
      volume: '2 litres',
      servings: 8,
      slug: 'asun_2l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790943/em2zviywyhg8wuxaciwr.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly roasted asun barbeque.',
    },
    {
      name: 'Asun',
      volume: '2.5 litres',
      servings: 12,
      slug: 'asun_2.5l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790943/em2zviywyhg8wuxaciwr.png`,
      price: 9000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly roasted asun barbeque.',
    },
    // Nkwobi
    {
      name: 'Nkwobi',
      volume: '1 litre',
      servings: 4,
      slug: 'nkwobi_1l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790979/fh5uwmdzdxvkjyx5fj48.png`,
      featuredImage: `/images/nkwobi-banner.png`,
      isFeatured: true,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked spicy nkwobi with isi ewu.',
    },
    {
      name: 'Nkwobi',
      volume: '2 litres',
      servings: 8,
      slug: 'nkwobi_2l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790979/fh5uwmdzdxvkjyx5fj48.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked spicy nkwobi with isi ewu.',
    },
    {
      name: 'Nkwobi',
      volume: '2.5 litres',
      servings: 12,
      slug: 'nkwobi_2.5l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652790979/fh5uwmdzdxvkjyx5fj48.png`,
      price: 9500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked spicy nkwobi with isi ewu.',
    },
    // Grilled Chicken
    {
      name: 'Grilled Chicken',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_chicken_1l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791015/ejdumonsxo9w6ep3zspx.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 5,
      numReviews: 12,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled chicken barbeque.',
    },
    {
      name: 'Grilled Chicken',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_chicken_2l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791015/ejdumonsxo9w6ep3zspx.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled chicken barbeque.',
    },
    {
      name: 'Grilled Chicken',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_chicken_2.5l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791015/ejdumonsxo9w6ep3zspx.png`,
      price: 9500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled chicken barbeque.',
    },
    // Grilled Turkey
    {
      name: 'Grilled Turkey',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_turkey_1l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791086/ctcpw51pjiw3cncmquty.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled turkey barbeque.',
    },
    {
      name: 'Grilled Turkey',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_turkey_2l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791086/ctcpw51pjiw3cncmquty.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled turkey barbeque.',
    },
    {
      name: 'Grilled Turkey',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_turkey_2.5l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791086/ctcpw51pjiw3cncmquty.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled turkey barbeque.',
    },
    // Grilled Beef
    {
      name: 'Grilled Beef',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_beef_1l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791132/y6xod62lqzvp6ls4ojij.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled beef barbeque.',
    },
    {
      name: 'Grilled Beef',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_beef_2l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791132/y6xod62lqzvp6ls4ojij.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled beef barbeque.',
    },
    {
      name: 'Grilled Beef',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_beef_2.5l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791132/y6xod62lqzvp6ls4ojij.png`,
      price: 9000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled beef barbeque.',
    },
    // Grilled Goat Meat
    {
      name: 'Grilled Goat Meat',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_goat_meat_1l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791173/fswcserisuusdzst3rww.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled goat meat barbeque.',
    },
    {
      name: 'Grilled Goat Meat',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_goat_meat_2l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791173/fswcserisuusdzst3rww.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled goat meat barbeque.',
    },
    {
      name: 'Grilled Goat Meat',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_goat_meat_2.5l',
      id: Id,
      category: 'Meats',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791173/fswcserisuusdzst3rww.png`,
      price: 9000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled  goat meat barbeque.',
    },
    // Grilled Croacker Fish
    {
      name: 'Grilled Croacker Fish',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_croacker_1l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791217/uqcysao3zqek4x6dhiq0.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled croacker fish barbeque.',
    },
    {
      name: 'Grilled Croacker Fish',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_croacker_2l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791217/uqcysao3zqek4x6dhiq0.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled croacker fish barbeque.',
    },
    {
      name: 'Grilled Croacker Fish',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_croacker_2.5l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791217/uqcysao3zqek4x6dhiq0.png`,
      price: 13500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled croacker fish barbeque.',
    },
    // Grilled Catfish
    {
      name: 'Grilled Catfish',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_catfish_1l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791263/rtikhkfoplacyzkaul2d.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 4,
      numReviews: 25,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled catfish barbeque.',
    },
    {
      name: 'Grilled Catfish',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_catfish_2l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791263/rtikhkfoplacyzkaul2d.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled catfish barbeque.',
    },
    {
      name: 'Grilled Catfish',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_catfish_2.5l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791263/rtikhkfoplacyzkaul2d.png`,
      price: 13500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled catfish barbeque.',
    },
    // Grilled Titus Fish
    {
      name: 'Grilled Titus Fish',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_titus_1l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791299/p3ovmdbzoypw6skslkzm.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled titus fish barbeque.',
    },
    {
      name: 'Grilled Titus Fish',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_titus_2l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791299/p3ovmdbzoypw6skslkzm.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled titus fish barbeque.',
    },
    {
      name: 'Grilled Titus Fish',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_titus_2.5l',
      id: Id,
      category: 'Fishes',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791299/p3ovmdbzoypw6skslkzm.png`,
      price: 13500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled titus fish barbeque.',
    },
    // Moi Moi
    {
      name: 'Moi Moi',
      volume: '1 wrap',
      servings: 1,
      slug: 'moi_moi_egg',
      id: Id,
      category: 'Wraps',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791342/y98jswtxtgit62273fc1.png`,
      price: 350,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A wrap of deliciously cooked moi moi with egg.',
    },
    {
      name: 'Moi Moi',
      volume: '1 wrap',
      servings: 1,
      slug: 'moi_moi_fish',
      id: Id,
      category: 'Wraps',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791541/yyhbpx1y8cpz1ulhyorf.png`,
      price: 350,
      vendor: 'Ahia Kitchen',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A wrap of deliciously cooked moi moi with fish.',
    },

    // Beans Porridge
    {
      name: 'Beans Porridge',
      volume: '1 litre',
      servings: 4,
      slug: 'beans_porridge',
      id: Id,
      category: 'Porridges',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791342/y98jswtxtgit62273fc1.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of delicious beans porridge garnished with plantains and your choice of either beef, fish or chicken.',
    },

    // Eguisi
    {
      name: 'Eguisi Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'eguisi_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791381/nsqhpi2ryuwdmifjmcyg.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Eguisi Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'eguisi_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791381/nsqhpi2ryuwdmifjmcyg.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Eguisi Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'eguisi_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791381/nsqhpi2ryuwdmifjmcyg.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    // Oha
    {
      name: 'Oha Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'oha_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791419/dy5zapbcahbnnsxolkjy.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Oha Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'oha_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791419/dy5zapbcahbnnsxolkjy.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Oha Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'oha_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791419/dy5zapbcahbnnsxolkjy.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Afang
    {
      name: 'Afang Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'afang_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791450/iyxip8eckmt8b9knaobt.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 5,
      numReviews: 11,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Afang Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'afang_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791450/iyxip8eckmt8b9knaobt.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Afang Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'afang_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791450/iyxip8eckmt8b9knaobt.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Banga
    {
      name: 'Banga Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'banga_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791493/u7zilo2unfqekl7kfgr2.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Banga Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'banga_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791493/u7zilo2unfqekl7kfgr2.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Banga Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'banga_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791493/u7zilo2unfqekl7kfgr2.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Bitter Leaf
    {
      name: 'Bitter Leaf Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'bitter_leaf_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791577/s8suhmmbsp50gon4ccam.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    {
      name: 'Bitter Leaf Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'bitter_leaf_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791577/s8suhmmbsp50gon4ccam.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    {
      name: 'Bitter Leaf Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'bitter_leaf_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791577/s8suhmmbsp50gon4ccam.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    //Vegetable
    {
      name: 'Vegetable Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'veg_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791619/g78kref5bciuaxlj4bni.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Vegetable Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'veg_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791619/g78kref5bciuaxlj4bni.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Vegetable Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'veg_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791619/g78kref5bciuaxlj4bni.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    // Okra
    {
      name: 'Okra Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'okra_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791661/sfrbdmarmfzrqcd6mpnm.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Okra Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'okra_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791661/sfrbdmarmfzrqcd6mpnm.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Okra Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'okra_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791661/sfrbdmarmfzrqcd6mpnm.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Ewedu
    {
      name: 'Ewedu Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'ewedu_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791701/hyxp1qkso8vy03qloqrl.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 4,
      numReviews: 14,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    {
      name: 'Ewedu Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'ewedu_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791701/hyxp1qkso8vy03qloqrl.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    {
      name: 'Ewedu Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'ewedu_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791701/hyxp1qkso8vy03qloqrl.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    // Gbegiri
    {
      name: 'Gbegiri Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'gbegiri_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791732/dxzbwwrbamgrwr4ywqga.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    {
      name: 'Gbegiri Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'gbegiri_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791732/dxzbwwrbamgrwr4ywqga.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    {
      name: 'Gbegiri Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'gbegiri_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791732/dxzbwwrbamgrwr4ywqga.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    // Tomato Stew
    {
      name: 'Tomato Stew',
      volume: '1 litre',
      servings: 4,
      slug: 'tomato_stew_1l',
      id: Id,
      category: 'Stews',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791766/dccl5mgwglokw6i3uj7d.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Tomato Stew',
      volume: '2 litres',
      servings: 8,
      slug: 'tomato_stew_2l',
      id: Id,
      category: 'Stews',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791766/dccl5mgwglokw6i3uj7d.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Tomato Stew',
      volume: '2.5 litres',
      servings: 12,
      slug: 'tomato_stew_2.5l',
      id: Id,
      category: 'Stews',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791766/dccl5mgwglokw6i3uj7d.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    // Ofada Sauce
    {
      name: 'Ofada Sauce',
      volume: '1 litre',
      servings: 4,
      slug: 'ofada_sauce_1l',
      id: Id,
      category: 'Sauces',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791807/eesxlbrfumbhxsdf2xtv.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    {
      name: 'Ofada Sauce',
      volume: '2 litres',
      servings: 8,
      slug: 'ofada_sauce_2l',
      id: Id,
      category: 'Sauces',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791807/eesxlbrfumbhxsdf2xtv.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    {
      name: 'Ofada Sauce',
      volume: '2.5 litres',
      servings: 12,
      slug: 'ofada_sauce_2.5l',
      id: Id,
      category: 'Sauces',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791807/eesxlbrfumbhxsdf2xtv.png`,
      price: 9500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    // White Soup
    {
      name: 'White Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'white_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791861/pekazx8rq5k847wwzbmi.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 4,
      numReviews: 10,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    {
      name: 'White Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'white_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791861/pekazx8rq5k847wwzbmi.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    {
      name: 'White Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'white_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791861/pekazx8rq5k847wwzbmi.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    // Eforiro
    {
      name: 'Eforiro Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'efo_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791902/sbt4a80eu2uc3g6bvotg.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    {
      name: 'Eforiro Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'efo_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791902/sbt4a80eu2uc3g6bvotg.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    {
      name: 'Eforiro Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'efo_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791902/sbt4a80eu2uc3g6bvotg.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    // Curry Sauce
    {
      name: 'Curry Sauce',
      volume: '1 litre',
      servings: 4,
      slug: 'curry_sauce_1l',
      id: Id,
      category: 'Sauces',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791935/gjrhfqzbvfkbfsqquryy.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    {
      name: 'Curry Sauce',
      volume: '2 litres',
      servings: 8,
      slug: 'curry_sauce_2l',
      id: Id,
      category: 'Sauces',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791935/gjrhfqzbvfkbfsqquryy.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    {
      name: 'Curry Sauce',
      volume: '2.5 litres',
      servings: 12,
      slug: 'curry_sauce_2.5l',
      id: Id,
      category: 'Sauces',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791935/gjrhfqzbvfkbfsqquryy.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    // Fisherman Soup
    {
      name: 'Fisherman Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'fisherman_soup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791973/sksm12lb81a2ytv7anpy.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    {
      name: 'Fisherman Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'fisherman_soup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791973/sksm12lb81a2ytv7anpy.png`,
      price: 9500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    {
      name: 'Fisherman Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fisherman_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652791973/sksm12lb81a2ytv7anpy.png`,
      price: 11000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    // Catfish Pepper Soup
    {
      name: 'Catfish Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'catfish_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792009/gclaiptaz4upnfnvncp9.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 4,
      numReviews: 15,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    {
      name: 'Catfish Pepper Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'catfish_peppersoup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792009/gclaiptaz4upnfnvncp9.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    {
      name: 'Catfish Pepper Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'catfish_peppersoup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792009/gclaiptaz4upnfnvncp9.png`,
      price: 11000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    // Goat Meat Pepper Soup
    {
      name: 'Goat Meat Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'goatmeat_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792047/hjgw4db5urka2opdac5p.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    {
      name: 'Goat Meat Pepper Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'goatmeat_peppersoup_2l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792047/hjgw4db5urka2opdac5p.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    {
      name: 'Goat Meat Pepper Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'goatmeat_peppersoup_2.5l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792047/hjgw4db5urka2opdac5p.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    // Cow Tail Pepper Soup
    {
      name: 'Cow Tail Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'cowtail_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792079/ffcmnwmigma6sna6arla.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with cow tail.',
    },
    // Yam Porridge
    {
      name: 'Yam Porridge',
      volume: '1 litre',
      servings: 4,
      slug: 'yam_porridge',
      id: Id,
      category: 'Porridges',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792130/dma0myl1nnx7k24inmte.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'A pot of delicious yam porridge garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    // Fried Plantain
    {
      name: 'Fried Plantain',
      volume: '1 litre',
      servings: 4,
      slug: 'fried_plantain_1l',
      id: Id,
      category: 'Fries',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792167/etiok5slefi0ora3vamk.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried plantain.',
    },
    {
      name: 'Fried Plantain',
      volume: '2 litres',
      servings: 8,
      slug: 'fried_plantain_2l',
      id: Id,
      category: 'Fries',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792167/etiok5slefi0ora3vamk.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried plantain.',
    },
    {
      name: 'Fried Plantain',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fried_plantain_2.5l',
      id: Id,
      category: 'Fries',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792167/etiok5slefi0ora3vamk.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried plantain.',
    },
    // Fried Potatoes
    {
      name: 'Fried Potatoe Chips',
      volume: '1 litre',
      servings: 4,
      slug: 'fried_potatoes_1l',
      id: Id,
      category: 'Fries',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792203/shmguchbntqljkoxmfxo.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried potatoe chips.',
    },
    {
      name: 'Fried Potatoe Chips',
      volume: '2 litres',
      servings: 8,
      slug: 'fried_potatoes_2l',
      id: Id,
      category: 'Fries',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792203/shmguchbntqljkoxmfxo.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried potatoe chips.',
    },
    {
      name: 'Fried Potatoes',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fried_potatoes_2.5l',
      id: Id,
      category: 'Fries',
      image: `https://res.cloudinary.com/waine-taylor/image/upload/v1652792203/shmguchbntqljkoxmfxo.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried potatoe chips.',
    },
  ],
};

export default data;
