import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';
const Id = uuidv4();
console.log(uuidv4());

const data = {
  users: [
    {
      firstName: 'John',
      lastName: 'Doe',
      email: 'admin@example.com',
      password: bcrypt.hashSync('admin1234'),
      phone: '9012345678',
      isAdmin: true,
    },
    {
      firstName: 'Manchi',
      lastName: 'Lee',
      email: 'user@example.com',
      password: bcrypt.hashSync('user1234'),
      phone: '9012345678',
      isAdmin: false,
    },
  ],
  products: [
    // Abacha
    {
      name: 'Abacha',
      volume: '1 litre',
      servings: 4,
      slug: 'abacha_1l',
      id: Id,
      category: 'Salads',
      image: `/images/abacha.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous Abacha and Ugba garnished with fish, kpomo and vegetables.',
    },
    {
      name: 'Abacha',
      volume: '2 litres',
      servings: 8,
      slug: 'abacha_2l',
      id: Id,
      category: 'Salads',
      image: `/images/abacha.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous Abacha and Ugba garnished with fish, kpomo and vegetables.',
    },
    {
      name: 'Abacha',
      volume: '2.5 litres',
      servings: 12,
      slug: 'abacha_2.5l',
      id: Id,
      category: 'Salads',
      image: `/images/abacha.png`,
      price: 9000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous Abacha and Ugba garnished with fish, kpomo and vegetables.',
    },
    // Chicken Salad
    {
      name: 'Chicken Salad',
      volume: '1 litre',
      servings: 4,
      slug: 'chicken_salad_1l',
      id: Id,
      category: 'Salads',
      image: `/images/chicken_salad.png`,
      price: 2500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous chicken salad.',
    },
    {
      name: 'Chicken Salad',
      volume: '2 litres',
      servings: 8,
      slug: 'chicken_salad_2l',
      id: Id,
      category: 'Salads',
      image: `/images/chicken_salad.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous chicken salad.',
    },
    {
      name: 'Chicken Salad',
      volume: '2.5 litres',
      servings: 12,
      slug: 'chicken_salad_2.5l',
      id: Id,
      category: 'Salads',
      image: `/images/chicken_salad.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous chicken salad.',
    },
    // Fish Salad
    {
      name: 'Fish Salad',
      volume: '1 litre',
      servings: 4,
      slug: 'fish_salad_1l',
      id: Id,
      category: 'Salads',
      image: `/images/fish_salad.png`,
      price: 2500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous fish salad.',
    },
    {
      name: 'Fish Salad',
      volume: '2 litres',
      servings: 8,
      slug: 'fish_salad_2l',
      id: Id,
      category: 'Salads',
      image: `/images/fish_salad.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous fish salad.',
    },
    {
      name: 'Fish Salad',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fish_salad_2.5l',
      id: Id,
      category: 'Salads',
      image: `/images/fish_salad.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous fish salad.',
    },
    // Native Rice
    {
      name: 'Native Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'native_rice_1l',
      id: Id,
      category: 'Rice',
      image: `/images/native_rice.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian native rice.',
    },
    {
      name: 'Native Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'native_rice_2l',
      id: Id,
      category: 'Rice',
      image: `/images/native_rice.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian native rice.',
    },
    {
      name: 'Native Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'native_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/native_rice.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian native rice.',
    },
    // Fried Rice
    {
      name: 'Fried Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'fried_rice_1l',
      id: Id,
      category: 'Rice',
      image: `/images/fried_rice.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian fried rice.',
    },
    {
      name: 'Fried Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'fried_rice_2l',
      id: Id,
      category: 'Rice',
      image: `/images/fried_rice.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian fried rice.',
    },
    {
      name: 'Fried Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fried_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/fried_rice.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian fried rice.',
    },
    // Jollof Rice
    {
      name: 'Jollof Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'jollof_rice_1l',
      id: Id,
      category: 'Rice',
      image: `/images/jollof_rice.png`,
      featuredImage: `/images/jollof_rice-banner.png`,
      isFeatured: true,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian jollof rice.',
    },
    {
      name: 'Jollof Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'jollof_rice_2l',
      id: Id,
      category: 'Rice',
      image: `/images/jollof_rice.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian jollof rice.',
    },
    {
      name: 'Jollof Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'jollof_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/jollof_rice.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian jollof rice.',
    },
    // White Rice
    {
      name: 'White Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'white_rice_1l',
      id: Id,
      category: 'Rice',
      image: `/images/white_rice.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice.',
    },
    {
      name: 'White Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'white_rice_2l',
      id: Id,
      category: 'Rice',
      image: `/images/white_rice.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice.',
    },
    {
      name: 'White Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'white_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/white_rice.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice.',
    },
    // Ofada Rice
    {
      name: 'Ofada Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'ofada_rice_1l',
      id: Id,
      category: 'Rice',
      image: `/images/ofada_rice.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian ofada rice.',
    },
    {
      name: 'Ofada Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'ofada_rice_2l',
      id: Id,
      category: 'Rice',
      image: `/images/ofada_rice.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian ofada rice.',
    },
    {
      name: 'Ofada Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'ofada_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/ofada_rice.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian ofada rice.',
    },
    // Palm Oil Rice
    {
      name: 'Palm Oil Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'palm_rice_1l',
      id: Id,
      category: 'Rice',
      image: `/images/palm_rice.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian palm oil rice.',
    },
    {
      name: 'Palm Oil Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'palm_rice_2l',
      id: Id,
      category: 'Rice',
      image: `/images/palm_rice.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian palm oil rice.',
    },
    {
      name: 'Palm Oil Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'palm_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/palm_rice.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly made Nigerian palm oil rice.',
    },
    // Seafood Fried Rice
    {
      name: 'Seafood Fried Rice',
      volume: '1 litre',
      servings: 4,
      slug: 'seafood_rice_1l',
      id: Id,
      category: 'Rice',
      image: `/images/seafood_rice.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked seafood fried rice.',
    },
    {
      name: 'Seafood Fried Rice',
      volume: '2 litres',
      servings: 8,
      slug: 'seafood_rice_2l',
      id: Id,
      category: 'Rice',
      image: `/images/seafood_rice.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked seafood fried rice.',
    },
    {
      name: 'Seafood Fried Rice',
      volume: '2.5 litres',
      servings: 12,
      slug: 'seafood_rice_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/seafood_rice.png`,
      price: 10000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked seafood fried rice.',
    },
    //White Rice & Beans
    {
      name: 'White Rice & Beans',
      volume: '1 litre',
      servings: 4,
      slug: 'w_rice_beans_1l',
      id: Id,
      category: 'Rice',
      image: `/images/w_rice_beans.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice and beans .',
    },
    {
      name: 'White Rice & Beans',
      volume: '2 litres',
      servings: 8,
      slug: 'w_rice_beans_2l',
      id: Id,
      category: 'Rice',
      image: `/images/w_rice_beans.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice and beans .',
    },
    {
      name: 'White Rice & Beans',
      volume: '2.5 litres',
      servings: 12,
      slug: 'w_rice_beans_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/w_rice_beans.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked white rice and beans .',
    },
    // Jollof Rice & Beans
    {
      name: 'Jollof Rice & Beans',
      volume: '1 litre',
      servings: 4,
      slug: 'j_rice_beans_1l',
      id: Id,
      category: 'Rice',
      image: `/images/j_rice_beans.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked jollof rice and beans .',
    },
    {
      name: 'Jollof Rice & Beans',
      volume: '2 litres',
      servings: 8,
      slug: 'j_rice_beans_2l',
      id: Id,
      category: 'Rice',
      image: `/images/j_rice_beans.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked jollof rice and beans .',
    },
    {
      name: 'Jollof Rice & Beans',
      volume: '2.5 litres',
      servings: 12,
      slug: 'j_rice_beans_2.5l',
      id: Id,
      category: 'Rice',
      image: `/images/j_rice_beans.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly cooked jollof rice and beans .',
    },
    // Jollof Spaghetti
    {
      name: 'Jollof Spaghetti',
      volume: '1 litre',
      servings: 4,
      slug: 'jollof_spaghetti_1l',
      id: Id,
      category: 'Pasta',
      image: `/images/jollof_spaghetti.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian jollof spaghetti.',
    },
    {
      name: 'Jollof Spaghetti',
      volume: '2 litres',
      servings: 8,
      slug: 'jollof_spaghetti_2l',
      id: Id,
      category: 'Pasta',
      image: `/images/jollof_spaghetti.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian jollof spaghetti.',
    },
    {
      name: 'Jollof Spaghetti',
      volume: '2.5 litres',
      servings: 12,
      slug: 'jollof_spaghetti_2.5l',
      id: Id,
      category: 'Pasta',
      image: `/images/jollof_spaghetti.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian jollof spaghetti.',
    },
    // Seafood Spaghetti
    {
      name: 'Seafood Spaghetti',
      volume: '1 litre',
      servings: 4,
      slug: 'seafood_spaghetti_1l',
      id: Id,
      category: 'Pasta',
      image: `/images/seafood_spaghetti.png`,
      featuredImage: `/images/seafood_spaghetti-banner.png`,
      isFeatured: true,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian seafood spaghetti.',
    },
    {
      name: 'Seafood Spaghetti',
      volume: '2 litres',
      servings: 8,
      slug: 'seafood_spaghetti_2l',
      id: Id,
      category: 'Pasta',
      image: `/images/seafood_spaghetti.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian seafood spaghetti.',
    },
    {
      name: 'Seafood Spaghetti',
      volume: '2.5 litres',
      servings: 12,
      slug: 'seafood_spaghetti_2.5l',
      id: Id,
      category: 'Pasta',
      image: `/images/seafood_spaghetti.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked Nigerian seafood spaghetti.',
    },
    // Asun
    {
      name: 'Asun',
      volume: '1 litre',
      servings: 4,
      slug: 'asun_1l',
      id: Id,
      category: 'Meats',
      image: `/images/asun.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 4.5,
      numReviews: 15,
      countInStock: 20,
      description: 'A pot of sumptuous freshly roasted asun barbeque.',
    },
    {
      name: 'Asun',
      volume: '2 litres',
      servings: 8,
      slug: 'asun_2l',
      id: Id,
      category: 'Meats',
      image: `/images/asun.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly roasted asun barbeque.',
    },
    {
      name: 'Asun',
      volume: '2.5 litres',
      servings: 12,
      slug: 'asun_2.5l',
      id: Id,
      category: 'Meats',
      image: `/images/asun.png`,
      price: 9000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly roasted asun barbeque.',
    },
    // Nkwobi
    {
      name: 'Nkwobi',
      volume: '1 litre',
      servings: 4,
      slug: 'nkwobi_1l',
      id: Id,
      category: 'Meats',
      image: `/images/nkwobi.png`,
      featuredImage: `/images/nkwobi-banner.png`,
      isFeatured: true,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked spicy nkwobi with isi ewu.',
    },
    {
      name: 'Nkwobi',
      volume: '2 litres',
      servings: 8,
      slug: 'nkwobi_2l',
      id: Id,
      category: 'Meats',
      image: `/images/nkwobi.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked spicy nkwobi with isi ewu.',
    },
    {
      name: 'Nkwobi',
      volume: '2.5 litres',
      servings: 12,
      slug: 'nkwobi_2.5l',
      id: Id,
      category: 'Meats',
      image: `/images/nkwobi.png`,
      price: 9500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of sumptuous freshly cooked spicy nkwobi with isi ewu.',
    },
    // Grilled Chicken
    {
      name: 'Grilled Chicken',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_chicken_1l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_chicken.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 5,
      numReviews: 12,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled chicken barbeque.',
    },
    {
      name: 'Grilled Chicken',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_chicken_2l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_chicken.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled chicken barbeque.',
    },
    {
      name: 'Grilled Chicken',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_chicken_2.5l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_chicken.png`,
      price: 9500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled chicken barbeque.',
    },
    // Grilled Turkey
    {
      name: 'Grilled Turkey',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_turkey_1l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_turkey.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled turkey barbeque.',
    },
    {
      name: 'Grilled Turkey',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_turkey_2l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_turkey.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled turkey barbeque.',
    },
    {
      name: 'Grilled Turkey',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_turkey_2.5l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_turkey.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled turkey barbeque.',
    },
    // Grilled Beef
    {
      name: 'Grilled Beef',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_beef_1l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_beef.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled beef barbeque.',
    },
    {
      name: 'Grilled Beef',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_beef_2l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_beef.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled beef barbeque.',
    },
    {
      name: 'Grilled Beef',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_beef_2.5l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_beef.png`,
      price: 9000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled beef barbeque.',
    },
    // Grilled Goat Meat
    {
      name: 'Grilled Goat Meat',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_goat_meat_1l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_goat_meat.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled goat meat barbeque.',
    },
    {
      name: 'Grilled Goat Meat',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_goat_meat_2l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_goat_meat.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled goat meat barbeque.',
    },
    {
      name: 'Grilled Goat Meat',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_goat_meat_2.5l',
      id: Id,
      category: 'Meats',
      image: `/images/grilled_goat_meat.png`,
      price: 9000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled  goat meat barbeque.',
    },
    // Grilled Croacker Fish
    {
      name: 'Grilled Croacker Fish',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_croacker_1l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_croacker.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled croacker fish barbeque.',
    },
    {
      name: 'Grilled Croacker Fish',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_croacker_2l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_croacker.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled croacker fish barbeque.',
    },
    {
      name: 'Grilled Croacker Fish',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_croacker_2.5l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_croacker.png`,
      price: 13500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled croacker fish barbeque.',
    },
    // Grilled Catfish
    {
      name: 'Grilled Catfish',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_catfish_1l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_catfish.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 4.5,
      numReviews: 90,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled catfish barbeque.',
    },
    {
      name: 'Grilled Catfish',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_catfish_2l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_catfish.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled catfish barbeque.',
    },
    {
      name: 'Grilled Catfish',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_catfish_2.5l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_catfish.png`,
      price: 13500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled catfish barbeque.',
    },
    // Grilled Titus Fish
    {
      name: 'Grilled Titus Fish',
      volume: '1 litre',
      servings: 4,
      slug: 'grilled_titus_1l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_titus.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled titus fish barbeque.',
    },
    {
      name: 'Grilled Titus Fish',
      volume: '2 litres',
      servings: 8,
      slug: 'grilled_titus_2l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_titus.png`,
      price: 10500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled titus fish barbeque.',
    },
    {
      name: 'Grilled Titus Fish',
      volume: '2.5 litres',
      servings: 12,
      slug: 'grilled_titus_2.5l',
      id: Id,
      category: 'Fishes',
      image: `/images/grilled_titus.png`,
      price: 13500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A pot of sumptuous freshly grilled titus fish barbeque.',
    },
    // Moi Moi
    {
      name: 'Moi Moi',
      volume: '1 wrap',
      servings: 1,
      slug: 'moi_moi_egg',
      id: Id,
      category: 'Wraps',
      image: `/images/moi_moi_egg.png`,
      price: 350,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A wrap of deliciously cooked moi moi with egg.',
    },
    {
      name: 'Moi Moi',
      volume: '1 wrap',
      servings: 1,
      slug: 'moi_moi_fish',
      id: Id,
      category: 'Wraps',
      image: `/images/moi_moi_fish.png`,
      price: 350,
      vendor: 'Ahia Kitchen',
      rating: 5,
      numReviews: 10,
      countInStock: 20,
      description: 'A wrap of deliciously cooked moi moi with fish.',
    },

    // Beans Porridge
    {
      name: 'Beans Porridge',
      volume: '1 litre',
      servings: 4,
      slug: 'beans_porridge',
      id: Id,
      category: 'Porridges',
      image: `/images/beans_porridge.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description:
        'A pot of delicious beans porridge garnished with plantains and your choice of either beef, fish or chicken.',
    },

    // Eguisi
    {
      name: 'Eguisi Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'eguisi_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/eguisi_soup.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Eguisi Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'eguisi_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/eguisi_soup.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Eguisi Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'eguisi_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/eguisi_soup.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 30,
      description:
        'A pot of freshly cooked eguisi soup garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    // Oha
    {
      name: 'Oha Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'oha_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/oha_soup.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Oha Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'oha_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/oha_soup.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Oha Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'oha_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/oha_soup.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked oha soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Afang
    {
      name: 'Afang Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'afang_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/afang_soup.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 5,
      numReviews: 11,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Afang Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'afang_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/afang_soup.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Afang Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'afang_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/afang_soup.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked afang soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Banga
    {
      name: 'Banga Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'banga_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/banga_soup.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Banga Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'banga_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/banga_soup.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Banga Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'banga_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/banga_soup.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked banga soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Bitter Leaf
    {
      name: 'Bitter Leaf Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'bitter_leaf_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/bitterleaf_soup.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    {
      name: 'Bitter Leaf Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'bitter_leaf_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/bitterleaf_soup.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    {
      name: 'Bitter Leaf Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'bitter_leaf_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/bitterleaf_soup.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 0,
      description:
        'A pot of freshly cooked bitter leaf soup garnished with your choice of either beef, fish or chicken.',
    },
    //Vegetable
    {
      name: 'Vegetable Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'veg_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/vegetable_soup.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Vegetable Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'veg_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/vegetable_soup.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Vegetable Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'veg_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/vegetable_soup.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked vegetable soup garnished with offals and your choice of either beef, fish or chicken.',
    },
    // Okra
    {
      name: 'Okra Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'okra_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/okra_soup.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Okra Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'okra_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/okra_soup.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Okra Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'okra_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/okra_soup.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked okra soup garnished with offals, vegetables and your choice of either beef, fish or chicken.',
    },
    // Ewedu
    {
      name: 'Ewedu Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'ewedu_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/ewedu_soup.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 4.5,
      numReviews: 14,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    {
      name: 'Ewedu Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'ewedu_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/ewedu_soup.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    {
      name: 'Ewedu Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'ewedu_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/ewedu_soup.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ewedu soup .',
    },
    // Gbegiri
    {
      name: 'Gbegiri Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'gbegiri_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/gbegiri_soup.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    {
      name: 'Gbegiri Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'gbegiri_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/gbegiri_soup.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    {
      name: 'Gbegiri Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'gbegiri_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/gbegiri_soup.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked gbegiri soup .',
    },
    // Tomato Stew
    {
      name: 'Tomato Stew',
      volume: '1 litre',
      servings: 4,
      slug: 'tomato_stew_1l',
      id: Id,
      category: 'Stews',
      image: `/images/tomato_stew.png`,
      price: 3500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Tomato Stew',
      volume: '2 litres',
      servings: 8,
      slug: 'tomato_stew_2l',
      id: Id,
      category: 'Stews',
      image: `/images/tomato_stew.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    {
      name: 'Tomato Stew',
      volume: '2.5 litres',
      servings: 12,
      slug: 'tomato_stew_2.5l',
      id: Id,
      category: 'Stews',
      image: `/images/tomato_stew.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked tomato stew garnished with offals and your choice of either beef, fish or chicken.',
    },
    // Ofada Sauce
    {
      name: 'Ofada Sauce',
      volume: '1 litre',
      servings: 4,
      slug: 'ofada_sauce_1l',
      id: Id,
      category: 'Sauces',
      image: `/images/ofada_sauce.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    {
      name: 'Ofada Sauce',
      volume: '2 litres',
      servings: 8,
      slug: 'ofada_sauce_2l',
      id: Id,
      category: 'Sauces',
      image: `/images/ofada_sauce.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    {
      name: 'Ofada Sauce',
      volume: '2.5 litres',
      servings: 12,
      slug: 'ofada_sauce_2.5l',
      id: Id,
      category: 'Sauces',
      image: `/images/ofada_sauce.png`,
      price: 9500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked ofada sauce.',
    },
    // White Soup
    {
      name: 'White Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'white_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/white_soup.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 4,
      numReviews: 10,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    {
      name: 'White Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'white_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/white_soup.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    {
      name: 'White Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'white_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/white_soup.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked white soup with an assortment of animal protein.',
    },
    // Eforiro
    {
      name: 'Eforiro Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'efo_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/efo_soup.png`,
      price: 4000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    {
      name: 'Eforiro Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'efo_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/efo_soup.png`,
      price: 5500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    {
      name: 'Eforiro Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'efo_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/efo_soup.png`,
      price: 7500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked eforiro with fresh vegetables.',
    },
    // Curry Sauce
    {
      name: 'Curry Sauce',
      volume: '1 litre',
      servings: 4,
      slug: 'curry_sauce_1l',
      id: Id,
      category: 'Sauces',
      image: `/images/curry_sauce.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    {
      name: 'Curry Sauce',
      volume: '2 litres',
      servings: 8,
      slug: 'curry_sauce_2l',
      id: Id,
      category: 'Sauces',
      image: `/images/curry_sauce.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    {
      name: 'Curry Sauce',
      volume: '2.5 litres',
      servings: 12,
      slug: 'curry_sauce_2.5l',
      id: Id,
      category: 'Sauces',
      image: `/images/curry_sauce.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of freshly cooked spicy curry sauce.',
    },
    // Fisherman Soup
    {
      name: 'Fisherman Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'fisherman_soup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/fisherman_soup.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    {
      name: 'Fisherman Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'fisherman_soup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/fisherman_soup.png`,
      price: 9500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    {
      name: 'Fisherman Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fisherman_soup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/fisherman_soup.png`,
      price: 11000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description: 'A pot of freshly cooked fisherman soup.',
    },
    // Catfish Pepper Soup
    {
      name: 'Catfish Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'catfish_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/catfish_peppersoup.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 4.5,
      numReviews: 15,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    {
      name: 'Catfish Pepper Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'catfish_peppersoup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/catfish_peppersoup.png`,
      price: 8500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    {
      name: 'Catfish Pepper Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'catfish_peppersoup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/catfish_peppersoup.png`,
      price: 11000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 24,
      description:
        'A pot of freshly cooked pepper soup garnished with catfish.',
    },
    // Goat Meat Pepper Soup
    {
      name: 'Goat Meat Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'goatmeat_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/goatmeat_peppersoup.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    {
      name: 'Goat Meat Pepper Soup',
      volume: '2 litres',
      servings: 8,
      slug: 'goatmeat_peppersoup_2l',
      id: Id,
      category: 'Soups',
      image: `/images/goatmeat_peppersoup.png`,
      price: 6500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    {
      name: 'Goat Meat Pepper Soup',
      volume: '2.5 litres',
      servings: 12,
      slug: 'goatmeat_peppersoup_2.5l',
      id: Id,
      category: 'Soups',
      image: `/images/goatmeat_peppersoup.png`,
      price: 8000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with goat meat.',
    },
    // Cow Tail Pepper Soup
    {
      name: 'Cow Tail Pepper Soup',
      volume: '1 litre',
      servings: 4,
      slug: 'cowtail_peppersoup_1l',
      id: Id,
      category: 'Soups',
      image: `/images/cowtail_peppersoup.png`,
      price: 4500,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description:
        'A pot of freshly cooked pepper soup garnished with cow tail.',
    },
    // Yam Porridge
    {
      name: 'Yam Porridge',
      volume: '1 litre',
      servings: 4,
      slug: 'yam_porridge',
      id: Id,
      category: 'Porridges',
      image: `/images/yam_porridge.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 10,
      description:
        'A pot of delicious yam porridge garnished with vegetables and your choice of either beef, fish or chicken.',
    },
    // Fried Plantain
    {
      name: 'Fried Plantain',
      volume: '1 litre',
      servings: 4,
      slug: 'fried_plantain_1l',
      id: Id,
      category: 'Fries',
      image: `/images/fried_plantain.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried plantain.',
    },
    {
      name: 'Fried Plantain',
      volume: '2 litres',
      servings: 8,
      slug: 'fried_plantain_2l',
      id: Id,
      category: 'Fries',
      image: `/images/fried_plantain.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried plantain.',
    },
    {
      name: 'Fried Plantain',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fried_plantain_2.5l',
      id: Id,
      category: 'Fries',
      image: `/images/fried_plantain.png`,
      price: 7000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried plantain.',
    },
    // Fried Potatoes
    {
      name: 'Fried Potatoe Chips',
      volume: '1 litre',
      servings: 4,
      slug: 'fried_potatoes_1l',
      id: Id,
      category: 'Fries',
      image: `/images/potatoe_chips.png`,
      price: 3000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried potatoe chips.',
    },
    {
      name: 'Fried Potatoe Chips',
      volume: '2 litres',
      servings: 8,
      slug: 'fried_potatoes_2l',
      id: Id,
      category: 'Fries',
      image: `/images/potatoe_chips.png`,
      price: 5000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried potatoe chips.',
    },
    {
      name: 'Fried Potatoes',
      volume: '2.5 litres',
      servings: 12,
      slug: 'fried_potatoes_2.5l',
      id: Id,
      category: 'Fries',
      image: `/images/potatoe_chips.png`,
      price: 6000,
      vendor: 'Ahia Kitchen',
      rating: 0,
      numReviews: 0,
      countInStock: 17,
      description: 'A pot of crispy fried potatoe chips.',
    },
  ],
};

export default data;
